language: csharp
mono: none
dotnet: 2.1
dist: trusty
sudo: required
script:
 - cd src
 - dotnet restore
 - dotnet build --configuration Release
 - dotnet test src/JKang.EventSourcing.Serialization.Json.Tests