language: csharp
mono: none
dotnet: 3.0
dist: trusty
sudo: required
script:
 - cd src
 - dotnet restore
 - dotnet build --configuration Release
 - dotnet test JKang.EventSourcing.Serialization.Json.Tests
 - dotnet test JKang.EventSourcing.Persistence.DynamoDB.Tests